name: Deploy

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "example/**"
  release:
    types:
      - published

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - uses: cachix/install-nix-action@6ed6027e4e9f222b485de42b929ec2fcaa1a16c7 # v30
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Build site
        run: |
          nix build .#site
          cp -rL result site

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@56afc609e74202f3d2f286f9b5e7eb93f3506c34 # v3
        with:
          path: site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4
